### ISSUE TITLE
Track all current and historical tested browser/OS combinations in one file

### ISSUE THREAD

**Issue by jeffcarp** [GoogleChrome/wptdashboard#47]
I think we should have a file in the root that enumerates all browser/OS combinations we currently test (and have ever tested) against. This would help with running the tests by making validating platform & version consistency easier. It would also help anyone who is using our data. One downside is that we'd need to add a new entry for Chrome and Firefox at least once every 6 weeks.

It could be named `browsers.yaml` or `browsers.json` with the following format:

```yaml
browsers:
  - platform_id: chrome-61-linux
    browser_name: chrome
    browser_version: 61.0
    os_name: linux
    os_version: 4.4
  - platform_id: firefox-56-windows-10
    browser_name: firefox
    browser_version: 56.0
    os_name: windows
    os_version: 10
```

Additional components:
- As part of our Python unit tests, validate this file (e.g. all `browser_name` are valid browser names)
- As part of the test runner, require passing in a valid `platform_id`
- Use `browsers.json` to control the initial test run summaries [test_handler.go](test_handler.go) (which should be renamed) loads
